### PR TITLE
add me as maintainer [ci skip] [skip ci]

### PR DESCRIPTION
**Pull request by carlodri**

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge/core can someone merge this please?

**Comment by bgruening** [comment]
@kszucs do you agree?

**Comment by kszucs** [comment]
@bgruening Sorry, I forgot to check again for the CI results (somewhy cricleci still gets triggered despite the skip ci). Welcome! :)

**Comment by carlodri** [comment]
Thanks @kszucs! Please take at look at my PR #5 and let me know if you agree.

**Pull request merged**
