### PR TITLE
move to cb3 syntax and try to make noarch

### PR DESCRIPTION
**Pull request by carlodri**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@conda-forge/aiofiles I added `noarch` at the expense of backwards compatibility (now Python 3.4+ is required). AFAIU concerning the downstream dependencies, this is not an issue. Let me know if this is ok.

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by kszucs** [comment]
Thanks @carlodri

**Pull request merged**
